name: pok3r_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mongo_dart: ^0.9.1
  uuid: ^3.0.6
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0
  nyxx: ^5.0.1
  nyxx_commands: ^5.0.2
#   path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.6.2
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
